### ISSUE TITLE
Question about the details of codebook

### ISSUE THREAD

**Issue by speedcell4** [kamwoh/orthohash#1]
Hi~ Thanks for sharing the source code.

I noticed you sample from a Bernoulli distribution to generate the codebook, but seems the codebook is not updated along the training. 

Would it be better to update it? Or is it unnecessary to do so? Do you have any theoretically proof on this part?

And also I noticed you emphasize *orthogonal* several times in your paper, does that mean as long as the orthogonality is ensured the updating of codebook is not needed?

**Comment by kamwoh** [comment]
Hi @speedcell4 ,

the codebook is a fixed codebook and will not be updated during training. We have done a version where we update the codebook **before the training**, that is running with `--codebook-method O`, this will maximize the Hamming distance between every class, we noticed a consistent improvement over all datasets and number of bits. See "D.3 Orthogonal Targets Generation" in the supplementary material for the experiment results.

At the moment we think it is already good by fixing the codebook, it is because when the training loss is minimized to 0, the learned codes have a maximum average hamming distance between every class (i.e., distance = #bits / 2), hence should be optimal. And this can be achieved because the codes in the codebook between each other are orthogonal (cosine similarity = 0 = #bits / 2).

**Comment by speedcell4** [comment]
Thank~
